.TH "md__c___users_clfma__desktop__faculdade__y2_s2__d_a__projeto1__read_me" 3 "Thu Apr 21 2022" "Projeto1_DA" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__c___users_clfma__desktop__faculdade__y2_s2__d_a__projeto1__read_me \- ReadMe 
\fBINSTRUÇÕES PARA CORRER O PROGRAMA / DEPENDÊNCIAS\fP
.PP
Não será necessário tomar nenhuma medida especial a não ser configurar as definições do programa de modo a garantir que a diretoria em que o programa corre é aquela que contem os source files e a pasta data\&.
.PP
\fBDIAGRAMA UML\fP
.PP
 
